### PR TITLE
Update for Agda standard library 0.14

### PR DESCRIPTION
**Pull request by mietek**
Minor conflicts.

### CODE REVIEW

**Comment by langston-barrett** [comment]
@gallais Is there anything holding this up? I currently can't build recent versions of `agdarsec` with `agdARGS`.

**Comment by gallais** [comment]
I have merged PR #2 which does basically the same but also gets rid of `Data.Nat.LTE`
which was made obsolete by the standard library's updates to `Data.Nat.Properties`.

It still needs some extra updates to be compatible with 0.15 but these are coming real soon.

**Comment by langston-barrett** [comment]
@gallais Thank you! Sorry for my impatience.

**Comment by gallais** [comment]
Not at all. I said I needed to look into making releases on github in November before
merging the PR and it turns out it was way easier than I anticipated! I just needed to
be pushed enough to finally do it.

**Pull request closed without merging**
